### ISSUE TITLE
Deleting of temporary files and loading non-existing sessions

### ISSUE THREAD

**Issue by ndyashas** [yashasbharadwaj111/GeneticAlgorithm#3]
Temporary files generated will stay there if not removed, which needs to be done.
By an explicit reset command ? not sure
Avoiding non-existent sessions at the start of a session ?
do we need to have this functionality ?

**Comment by Vaibhav530** [comment]
thinking of adding signals to delete temp files

**Comment by ndyashas** [comment]
> thinking of adding signals to delete temp files

Yup , would love to have an update on it

**Comment by Vaibhav530** [comment]
I took lot of time understanding how to make a pull request

**Comment by ndyashas** [comment]
Thanks a lot man !, as this issue was solved will close the issue. :
