### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by ndyashas** [yashasbharadwaj111/GeneticAlgorithm#5]
The code goes into infinite loop when the flag "mutation" is set to 1. 
Possibly due to bug in ga2/gaUtil/gaDeamon.mutateAgentObj() funtion.

**Comment by Vaibhav530** [comment]
i saw your code in gaDeamon.py line 48 expression:
sess.mutation>random.random
might cause infinite loop as random returns (0,1) when called and mutation is 1

**Comment by ndyashas** [comment]
Yup , but I though that and "itr" counter would break the loop after 10 iterations, that part of the code is not implimented correctly . You want to send a pull requiest with the fix ?

**Comment by Vaibhav530** [comment]
yup ill send
