### ISSUE TITLE
Implimentation for multi parent reproduction

### ISSUE THREAD

**Issue by ndyashas** [yashasbharadwaj111/GeneticAlgorithm#7]
Setting and using of the flag "genrateMode" in gaDisc needs to be implimented along with implimentation of multiparent reproduction functions.

**Comment by Vaibhav530** [comment]
is it children of more than two parents

**Comment by ndyashas** [comment]
yes it is. Currently only gaDeamon.aSexualRep() is implimented
gaDeamon.sexualRep() needs to be implimented too right ?
should we take 2 parents per child or more than that ?

**Comment by ndyashas** [comment]
Implimentation done
